"""Add snapshots and fix IA scores

Revision ID: 5d69459af49b
Revises: 
Create Date: 2026-08-08 07:10:24.185694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d69459af49b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.String(length=20), nullable=False),
    sa.Column('sum_of_scores', sa.Integer(), nullable=False),
    sa.Column('score_for_exams', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('university_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name'),
    sa.UniqueConstraint('university_id')
    )
    op.create_table('directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('education_degree', sa.Enum('BACHELOR', 'SPECIALIST', 'MASTER', 'POSTGRADUATE', name='educationdegree'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.Column('education_form', sa.Enum('FULL_TIME', 'PART_TIME', 'DISTANCE', name='educationform'), nullable=False),
    sa.Column('funding_type', sa.Enum('BUDGET', 'PAID', 'COMMERCIAL', 'SPECIAL_QUOTA', 'SEPARATE_QUOTA', 'TARGET', name='fundingtype'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('applicant_db_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('score_for_ia', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('has_original', sa.Boolean(), nullable=False),
    sa.Column('is_bvi', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('IN_CONTEST', 'AWAITING_RESULTS', 'AWAITING_CHECK', 'SUBMITTED', 'REJECTED', 'EXCLUDED', name='applicantconteststatus'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_db_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('applicant_db_id', 'direction_id', 'snapshot_id')
    )
    op.create_index(op.f('ix_applications_snapshot_id'), 'applications', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_snapshot_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('snapshots')
    op.drop_table('directions')
    op.drop_table('universities')
    op.drop_table('applicants')
    # ### end Alembic commands ###
